data_ingestion:
  workspace: "jacob-solawetz"
  project_name: "pascal-voc-2012"
  version: "1"
  format: "voc"

data_validation:
  required_files:
    - train
    - valid

data_transformation:
  resize: true
  image_size: [224, 224]
  flip_prob: 0.5

data_loader:
  train_batch_size: 8
  valid_batch_size: 8
  num_workers: 4
  pin_memory: true
  drop_last: true
